name: supply_chain_app
description: Supply Chain Intelligence - Logistics Hackathon Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Outputs/simulation_output.json
    - Outputs/dashboard_state.json
    - Outputs/failure_log.json
